# Generated by Django 3.1.7 on 2021-03-20 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_auto_20210320_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empolyee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='me.user')),
                ('phone', models.CharField(max_length=54)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_employee',
        ),
    ]
